name = "North Hole V2"
author = "Aero"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0f0d9110c4397f935afc37d77077515c30bb2b2823af85844379365ea20af28"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
