name = "North Hole V2"
author = "Aero"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ea4dfda55082fc110ae2bd106a0c50c4798fe76c0e9c49a527d59536d3cc39f"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
